---
- name: ELASTIC BEAT INSTALLATION
  hosts: localhost
  roles:
    - role: elastic.beats
  vars:
    beats_vesrsion: 7.16.3
    beat: metricbeat
    beat_conf:
      metric.modules:
      - system
      - kafka
    enable: true
